apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-deployment
  labels:
    app: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: dockangad/client-app:latest  # Replace with your image
        ports:
        - containerPort: 80
        env:
        - name: SERVER_URL
          value: "http://localhost:5000/message"  # Replace with your server URL

