apiVersion: v1
kind: Service
metadata:
  name: server1-service
spec:
  selector:
    app: server1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000  # Must match the containerPort specified in the Deployment
  type: ClusterIP  # Change to LoadBalancer or NodePort if external access is needed
